name: meta-env
description: Transposes meta-data to env vars
author: https://github.com/pecigonzalo
requirements: [
  "git",
]
configuration:
  properties:
    keys:
      type: [string, array]
  required:
    - keys
  additionalProperties: false
